<?php
/**
 * Implements hook_block_info().
 */
function tradexperts_category_block_info(){
	$blocks = array();
	$blocks['tradexperts_cate_investment'] = array(
    'info' => 'investment',
  );
	$blocks['tradexperts_training'] = array(
    'info' => 'training',
  );
	$blocks['tradexperts_pamm_accounts'] = array(
    'info' => 'PAMM accounts',
  );
	 return $blocks;
}
/**
 * Implements hook_block_view().
 */
function tradexperts_category_block_view($delta = ''){
	$block = array();
	switch ($delta) {
		case 'tradexperts_cate_investment':
			$result = db_select('node', 'n');
			$result->innerJoin("field_data_field_category", "c", "n.nid = c.entity_id and c.bundle = 'page' and c.entity_type = 'node'");
			$result->innerJoin("field_data_field_picture", "p", "n.nid = p.entity_id and p.bundle = 'page' and p.entity_type = 'node'");
			$result->innerJoin("file_managed", "m", "p.field_picture_fid = m.fid");
			$result->condition('n.type', 'page');
			$result->condition('c.field_category_tid', 1);
			$result->fields('m', array('filename', 'uri'));
			$result->fields('n', array('title', 'nid'));	
			$select = $result->execute()->fetchAll();
			$block['subject'] = t('investment');
      		$block['content'] = theme('tradexperts_categorys', array('select' => $select));
			break;

		case 'tradexperts_training':
			$result = db_select('node', 'n');
			$result->innerJoin("field_data_field_category", "c", "n.nid = c.entity_id and c.bundle = 'page' and c.entity_type = 'node'");
			$result->innerJoin("field_data_field_picture", "p", "n.nid = p.entity_id and p.bundle = 'page' and p.entity_type = 'node'");
			$result->innerJoin("file_managed", "m", "p.field_picture_fid = m.fid");
			$result->condition('n.type', 'page');
			$result->condition('c.field_category_tid', 2);
			$result->fields('m', array('filename', 'uri'));
			$result->fields('n', array('title', 'nid'));	
			$select = $result->execute()->fetchAll();
			$block['subject'] = t('training');
      		$block['content'] = theme('tradexperts_categorys', array('select' => $select));
			break;

		case 'tradexperts_pamm_accounts':
			$result = db_select('node', 'n');
			$result->innerJoin("field_data_field_category", "c", "n.nid = c.entity_id and c.bundle = 'page' and c.entity_type = 'node'");
			$result->innerJoin("field_data_field_picture", "p", "n.nid = p.entity_id and p.bundle = 'page' and p.entity_type = 'node'");
			$result->innerJoin("file_managed", "m", "p.field_picture_fid = m.fid");
			$result->condition('n.type', 'page');
			$result->condition('c.field_category_tid', 3);
			$result->fields('m', array('filename', 'uri'));
			$result->fields('n', array('title', 'nid'));	
			$select = $result->execute()->fetchAll();
			$block['subject'] = t('PAMM account');
      		$block['content'] = theme('tradexperts_categorys', array('select' => $select));
			break;
		
	}
	return $block;
}
/**
 * Implements hook_theme().
 */
function tradexperts_category_theme() {
	return array(
		'tradexperts_categorys' => array(
			'variables' => array(
				'select' => array(),
			),
			'path'     => drupal_get_path('module', 'tradexperts_category') . '/templates',
			'template' => 'tradexperts-categorys',
		),
	);
}